services:
  mysql:
    image: mysql:8.0
    container_name: rg-academy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rg_password_2026
      MYSQL_DATABASE: rg_academy
      MYSQL_USER: rg_admin
      MYSQL_PASSWORD: rg_password_2026
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
